services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Thang123"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    networks:
      - pre-network
    restart: always

networks:
  pre-network:
    driver: bridge