spring:
  application:
    name: app-report-generator
  datasource:
    platform:
      url: jdbc:postgresql://localhost:5432/platform
      jdbcUrl: ${spring.datasource.platform.url}
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: Thang123
#    customer:
#      url: jdbc:postgresql://localhost:5432/customer
#      jdbcUrl: ${spring.datasource.platform.url}
#      driver-class-name: org.postgresql.Driver
#      username: postgres
#      password: Thang123
#    transaction:
#      url: jdbc:postgresql://localhost:5432/transaction
#      jdbcUrl: ${spring.datasource.platform.url}
#      driver-class-name: org.postgresql.Driver
#      username: postgres
#      password: Thang123
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true

#logging:
#  level:
#    org:
#      springframework: DEBUG
